#!/usr/bin/env bash
# Synthesize each synthesizable block to real sky130hd standard cells and run
# static timing and power analysis on the resulting gate-level netlist.
#
# Usage:
#   bash asic/sta/run_ppa.sh                    # default block set, 10 ns
#   PERIODS="10 8 6 5 4" bash asic/sta/run_ppa.sh
#   BLOCKS=conv5x5_pe PERIODS=5 bash asic/sta/run_ppa.sh
#
# Why this exists alongside asic/openroad/: ORFS drives the full RTL-to-GDS
# flow, but its place-and-route stages need an embedded Python that is not
# available on this machine (see docs/PPA.md, "Toolchain notes"). Synthesis and
# STA do not, so this script gets real area/timing/power numbers out of the
# same PDK without depending on the broken stage.
#
# Everything written here is derived, not hand-entered. Numbers quoted in
# docs/PPA.md come from asic/sta/results/ppa_summary.csv.

set -euo pipefail

ORFS_ROOT="${ORFS_ROOT:-/root/OpenROAD-flow-scripts}"
PLATFORM_DIR="$ORFS_ROOT/flow/platforms/sky130hd"
LIB="$PLATFORM_DIR/lib/sky130_fd_sc_hd__tt_025C_1v80.lib"
TLEF="$PLATFORM_DIR/lef/sky130_fd_sc_hd.tlef"
LEF="$PLATFORM_DIR/lef/sky130_fd_sc_hd_merged.lef"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_HOME="$(cd "$HERE/../.." && pwd)"
OUT="$HERE/results"
WORK="$HERE/work"

for f in "$LIB" "$TLEF" "$LEF"; do
    [ -f "$f" ] || { echo "ERROR: missing PDK file $f" >&2; exit 1; }
done
for tool in yosys openroad; do
    command -v "$tool" >/dev/null 2>&1 || { echo "ERROR: $tool not on PATH" >&2; exit 1; }
done

BLOCKS="${BLOCKS:-conv5x5_row_mac requantize avg_pool2x2_int8 dense_row_mac conv5x5_pe}"
PERIODS="${PERIODS:-10}"

# Source list per block. Only blocks whose storage is real logic appear here;
# the memory-backed wrappers are excluded on purpose (docs/SEMICUSTOM_FLOW.md).
sources_for() {
    case "$1" in
        conv5x5_row_mac)  echo "rtl/conv5x5_row_mac.sv" ;;
        requantize)       echo "rtl/requantize.sv" ;;
        avg_pool2x2_int8) echo "rtl/avg_pool2x2_int8.sv" ;;
        dense_row_mac)    echo "rtl/dense_row_mac.sv" ;;
        conv5x5_pe)       echo "rtl/conv5x5_row_mac.sv rtl/requantize.sv rtl/conv5x5_pe.sv" ;;
        *) echo "ERROR: no source list for block '$1'" >&2 ; return 1 ;;
    esac
}

mkdir -p "$OUT" "$WORK"
CSV="$OUT/ppa_summary.csv"
echo "block,period_ns,cells,seq_cells,area_um2,wns_ns,whs_ns,tns_ns,crit_path_ns,power_total_w,timing_met" > "$CSV"

for block in $BLOCKS; do
    srcs="$(sources_for "$block")"
    for period in $PERIODS; do
        tag="${block}_${period}ns"
        netlist="$WORK/${tag}.mapped.v"
        ylog="$OUT/${tag}.yosys.log"
        slog="$OUT/${tag}.sta.log"

        # abc takes its delay target in ps.
        period_ps="$(awk -v p="$period" 'BEGIN{printf "%d", p*1000}')"

        cat > "$WORK/${tag}.ys" <<EOF
# Generated by asic/sta/run_ppa.sh -- do not edit.
# Load the cell interfaces as blackboxes first. Without this, abc -liberty
# instantiates sky130 cells whose module definitions yosys has never seen, so
# the later check pass cannot tell that .X/.Y are outputs, treats every cell
# connection as a load, and reports each output bit as "used but has no
# driver" on a netlist that is in fact fully driven.
read_liberty -lib $LIB
$(for s in $srcs; do echo "read_verilog -sv $PROJECT_HOME/$s"; done)
hierarchy -check -top $block
synth -top $block -flatten
dfflibmap -liberty $LIB
abc -liberty $LIB -D $period_ps
setundef -zero
opt_clean -purge
check
splitnets
opt_clean -purge
stat -liberty $LIB
write_verilog -noattr $netlist
EOF

        echo "== yosys : $block @ ${period} ns"
        yosys -q -l "$ylog" -s "$WORK/${tag}.ys" 2>&1 | tail -5 || {
            echo "   FAILED (see $ylog)"; continue; }

        echo "== sta   : $block @ ${period} ns"
        STA_LIB="$LIB" STA_TLEF="$TLEF" STA_LEF="$LEF" \
        STA_NETLIST="$netlist" STA_TOP="$block" STA_PERIOD="$period" \
            openroad -no_init -exit "$HERE/sta.tcl" > "$slog" 2>&1 || {
            echo "   FAILED (see $slog)"; continue; }

        # ---- harvest -------------------------------------------------------
        cells=$(awk '/Number of cells:/{n=$NF} END{print n+0}' "$ylog")
        seq=$(awk '/sky130_fd_sc_hd__(s?e?df)/{n+=$NF} END{print n+0}' "$ylog")
        area=$(awk '/Chip area for module/{a=$NF} END{printf "%.3f", a+0}' "$ylog")
        # sta.tcl prints setup slack then hold slack, both as "worst slack <v>".
        wns=$(awk '/^worst slack/{print $3; exit}' "$slog")
        whs=$(awk '/^worst slack/{n++; if(n==2){print $3; exit}}' "$slog")
        tns=$(awk '/^tns/{print $2; exit}' "$slog")
        power=$(awk '/^Total/{print $(NF-1); exit}' "$slog")
        # Critical path = period - WNS, i.e. the delay the netlist actually has.
        crit=$(awk -v p="$period" -v w="${wns:-}" 'BEGIN{if(w=="")print "";else printf "%.4f", p-w}')
        met=$(awk -v w="${wns:-}" 'BEGIN{if(w=="")print "unknown"; else if(w+0>=0)print "yes"; else print "no"}')

        echo "$block,$period,$cells,$seq,$area,${wns:-},${whs:-},${tns:-},${crit:-},${power:-},$met" >> "$CSV"
        echo "   cells=$cells seq=$seq area=${area}um2 wns=${wns:-?}ns power=${power:-?}W met=$met"
    done
done

echo
echo "== summary written to $CSV"
cat "$CSV"
