// Generated by golden/generate_vectors.py; do not hand edit.
// ---- tb_conv2d_engine.sv (first/legacy module; macros unprefixed) ----
`define TV_IN_H 7
`define TV_IN_W 8
`define TV_IN_CH 3
`define TV_OUT_CH 4
`define TV_OUT_H 3
`define TV_OUT_W 4
`define TV_SHIFT 7
`define TV_RELU 1'b1
`define TV_ACT_COUNT 168
`define TV_WGT_COUNT 300
`define TV_BIAS_COUNT 4
`define TV_CONN_COUNT 12
`define TV_OUT_COUNT 48

// ---- tb_avg_pool2x2_stream.sv ----
`define TV_POOL_IN_H 4
`define TV_POOL_IN_W 6
`define TV_POOL_IN_CH 2
`define TV_POOL_OUT_H 2
`define TV_POOL_OUT_W 3
`define TV_POOL_ACT_COUNT 48
`define TV_POOL_OUT_COUNT 12

// ---- tb_dense_engine.sv (F6 configuration) ----
`define TV_F6_IN_LEN 10
`define TV_F6_OUT_LEN 5
`define TV_F6_SHIFT 6
`define TV_F6_RELU 1'b1
`define TV_F6_ACT_COUNT 10
`define TV_F6_WGT_COUNT 50
`define TV_F6_BIAS_COUNT 5
`define TV_F6_OUT_COUNT 5

// ---- tb_classifier_argmax.sv ----
`define TV_CLS_IN_LEN 6
`define TV_CLS_NUM_CLASSES 4
`define TV_CLS_ACT_COUNT 6
`define TV_CLS_WGT_COUNT 24
`define TV_CLS_BIAS_COUNT 4
`define TV_CLS_EXPECTED_CLASS 3

// ---- tb_requantize.sv ----
`define TV_RQ_COUNT 5504

// ---- tb_extremes.sv (int8-extreme operands at maximum layer size) ----
`define TV_EX_IN_H 5
`define TV_EX_IN_W 5
`define TV_EX_IN_CH 16
`define TV_EX_OUT_CH 2
`define TV_EX_SHIFT 16
`define TV_EX_RELU 1'b0
`define TV_EX_ACT_COUNT 400
`define TV_EX_WGT_COUNT 800
`define TV_EX_BIAS_COUNT 2
`define TV_EX_CONN_COUNT 32
`define TV_EX_OUT_COUNT 2
`define TV_EX_PEAK_ACC 7502600

// Same DUT and same activations, weights cancelling to zero, shift 0, so the
// output is the accumulator itself and one wrong product is visible.
`define TV_EXC_SHIFT 0
`define TV_EXC_WGT_COUNT 800
`define TV_EXC_BIAS_COUNT 2
`define TV_EXC_OUT_COUNT 2

// Minimum legal conv configuration: 1 channel, 5x5 -> 1x1, one output beat.
`define TV_EXMIN_IN_H 5
`define TV_EXMIN_IN_W 5
`define TV_EXMIN_IN_CH 1
`define TV_EXMIN_OUT_CH 1
`define TV_EXMIN_SHIFT 12
`define TV_EXMIN_RELU 1'b0
`define TV_EXMIN_ACT_COUNT 25
`define TV_EXMIN_WGT_COUNT 25
`define TV_EXMIN_BIAS_COUNT 1
`define TV_EXMIN_CONN_COUNT 1
`define TV_EXMIN_OUT_COUNT 1

// ---- tb_extremes.sv dense case ----
`define TV_EXD_IN_LEN 120
`define TV_EXD_OUT_LEN 4
`define TV_EXD_SHIFT 16
`define TV_EXD_RELU 1'b0
`define TV_EXD_ACT_COUNT 120
`define TV_EXD_WGT_COUNT 480
`define TV_EXD_BIAS_COUNT 4
`define TV_EXD_OUT_COUNT 4
`define TV_EXD_PEAK_ACC 2950780

// ---- tb_lenet5_top.sv ----
`define TV_TOP_EXPECTED_CLASS 6
`define TV_TOP_WATCHDOG_CYCLES 600000
