// Generated by golden/generate_vectors.py; do not hand edit.
// ---- tb_conv2d_engine.sv (first/legacy module; macros unprefixed) ----
`define TV_IN_H 7
`define TV_IN_W 8
`define TV_IN_CH 3
`define TV_OUT_CH 4
`define TV_OUT_H 3
`define TV_OUT_W 4
`define TV_SHIFT 7
`define TV_RELU 1'b1
`define TV_ACT_COUNT 168
`define TV_WGT_COUNT 300
`define TV_BIAS_COUNT 4
`define TV_CONN_COUNT 12
`define TV_OUT_COUNT 48

// ---- tb_avg_pool2x2_stream.sv ----
`define TV_POOL_IN_H 4
`define TV_POOL_IN_W 6
`define TV_POOL_IN_CH 2
`define TV_POOL_OUT_H 2
`define TV_POOL_OUT_W 3
`define TV_POOL_ACT_COUNT 48
`define TV_POOL_OUT_COUNT 12

// ---- tb_dense_engine.sv (F6 configuration) ----
`define TV_F6_IN_LEN 10
`define TV_F6_OUT_LEN 5
`define TV_F6_SHIFT 6
`define TV_F6_RELU 1'b1
`define TV_F6_ACT_COUNT 10
`define TV_F6_WGT_COUNT 50
`define TV_F6_BIAS_COUNT 5
`define TV_F6_OUT_COUNT 5

// ---- tb_classifier_argmax.sv ----
`define TV_CLS_IN_LEN 6
`define TV_CLS_NUM_CLASSES 4
`define TV_CLS_ACT_COUNT 6
`define TV_CLS_WGT_COUNT 24
`define TV_CLS_BIAS_COUNT 4
`define TV_CLS_EXPECTED_CLASS 3

// ---- tb_requantize.sv ----
`define TV_RQ_COUNT 5504

// ---- tb_conv5x5_row_mac.sv ----
`define TV_MACC_COUNT 6592
`define TV_MACC_LANES 5
`define TV_MACC_PEAK_POS 81920
`define TV_MACC_PEAK_NEG -81280
`define TV_MACC_LANES_AT_MIN 5
`define TV_MACC_LANES_AT_MAX 5

// ---- tb_dense_row_mac.sv ----
`define TV_MACD_COUNT 9540
`define TV_MACD_LANES 8
`define TV_MACD_PEAK_POS 131072
`define TV_MACD_PEAK_NEG -130048
`define TV_MACD_LANES_AT_MIN 8
`define TV_MACD_LANES_AT_MAX 8

// ---- tb_conv5x5_pe_stream.sv ----
`define TV_PE_PIXELS 848
`define TV_PE_ROWS_TOTAL 3147
`define TV_PE_MAX_ROWS 8
`define TV_PE_SAT_HI 87
`define TV_PE_SAT_LO 80
`define TV_PE_RELU_CLAMPED 215
`define TV_PE_ONE_ROW 48
`define TV_PE_SHIFTS_USED 32
`define TV_PE_BACK_TO_BACK 428

// ---- tb_extremes.sv (int8-extreme operands at maximum layer size) ----
`define TV_EX_IN_H 5
`define TV_EX_IN_W 5
`define TV_EX_IN_CH 16
`define TV_EX_OUT_CH 2
`define TV_EX_SHIFT 16
`define TV_EX_RELU 1'b0
`define TV_EX_ACT_COUNT 400
`define TV_EX_WGT_COUNT 800
`define TV_EX_BIAS_COUNT 2
`define TV_EX_CONN_COUNT 32
`define TV_EX_OUT_COUNT 2
`define TV_EX_PEAK_ACC 7502600

// Same DUT and same activations, weights cancelling to zero, shift 0, so the
// output is the accumulator itself and one wrong product is visible.
`define TV_EXC_SHIFT 0
`define TV_EXC_WGT_COUNT 800
`define TV_EXC_BIAS_COUNT 2
`define TV_EXC_OUT_COUNT 2

// Minimum legal conv configuration: 1 channel, 5x5 -> 1x1, one output beat.
`define TV_EXMIN_IN_H 5
`define TV_EXMIN_IN_W 5
`define TV_EXMIN_IN_CH 1
`define TV_EXMIN_OUT_CH 1
`define TV_EXMIN_SHIFT 12
`define TV_EXMIN_RELU 1'b0
`define TV_EXMIN_ACT_COUNT 25
`define TV_EXMIN_WGT_COUNT 25
`define TV_EXMIN_BIAS_COUNT 1
`define TV_EXMIN_CONN_COUNT 1
`define TV_EXMIN_OUT_COUNT 1

// ---- tb_extremes.sv dense case ----
`define TV_EXD_IN_LEN 120
`define TV_EXD_OUT_LEN 4
`define TV_EXD_SHIFT 16
`define TV_EXD_RELU 1'b0
`define TV_EXD_ACT_COUNT 120
`define TV_EXD_WGT_COUNT 480
`define TV_EXD_BIAS_COUNT 4
`define TV_EXD_OUT_COUNT 4
`define TV_EXD_PEAK_ACC 2950780

// ---- tb_lenet5_top.sv ----
`define TV_TOP_EXPECTED_CLASS 6
`define TV_TOP_WATCHDOG_CYCLES 600000

// ---- tb_layer_shapes.sv ----
// C1: 1x32x32 -> 6x28x28, full connectivity
`define TV_LS_C1_ACT_COUNT 1024
`define TV_LS_C1_WGT_COUNT 150
`define TV_LS_C1_BIAS_COUNT 6
`define TV_LS_C1_OUT_COUNT 4704
`define TV_LS_C1_IN_CH 1
`define TV_LS_C1_OUT_CH 6
`define TV_LS_C1_IN_H 32
`define TV_LS_C1_IN_W 32

// C3: 6x14x14 -> 16x10x10, real sparse LeCun-98 connectivity
`define TV_LS_C3_ACT_COUNT 1176
`define TV_LS_C3_WGT_COUNT 2400
`define TV_LS_C3_BIAS_COUNT 16
`define TV_LS_C3_OUT_COUNT 1600
`define TV_LS_C3_IN_CH 6
`define TV_LS_C3_OUT_CH 16
`define TV_LS_C3_IN_H 14
`define TV_LS_C3_IN_W 14
`define TV_LS_C3_CONN_ONES 60

// C5: 16x5x5 -> 120x1x1, full connectivity -- MAX_OUT_CH reached standalone
`define TV_LS_C5_ACT_COUNT 400
`define TV_LS_C5_WGT_COUNT 48000
`define TV_LS_C5_BIAS_COUNT 120
`define TV_LS_C5_OUT_COUNT 120
`define TV_LS_C5_IN_CH 16
`define TV_LS_C5_OUT_CH 120
`define TV_LS_C5_IN_H 5
`define TV_LS_C5_IN_W 5

// F6: dense_engine 120 -> 84 -- MAX_OUT_LEN reached standalone
`define TV_LS_F6_ACT_COUNT 120
`define TV_LS_F6_WGT_COUNT 10080
`define TV_LS_F6_BIAS_COUNT 84
`define TV_LS_F6_OUT_COUNT 84
`define TV_LS_F6_IN_LEN 120
`define TV_LS_F6_OUT_LEN 84

// classifier stage: dense_engine 84 -> 10, shift 0 / relu off, same instance
// as F6 reconfigured -- out_acc_o is the signal classifier_argmax votes on
`define TV_LS_CLS_ACT_COUNT 84
`define TV_LS_CLS_WGT_COUNT 840
`define TV_LS_CLS_BIAS_COUNT 10
`define TV_LS_CLS_OUT_COUNT 10
`define TV_LS_CLS_IN_LEN 84
`define TV_LS_CLS_OUT_LEN 10
`define TV_LS_EXPECTED_CLASS 6

// ---- tb_trained_mnist.sv ----
`define TV_TR_NUM_IMAGES 10
`define TV_TR_LABEL_MATCHES 10
`define TV_TR_WATCHDOG_CYCLES 2000000
// Calibrated per-layer shifts, replacing the flat shift=7 every random-weight
// tier uses. tb_trained_mnist.sv passes these straight into lenet5_top's
// SHIFT_C1/C3/C5/F6 parameters, so this is also the only tier that drives the
// top level at anything other than its default shift values.
`define TV_TR_SHIFT_C1 9
`define TV_TR_SHIFT_C3 8
`define TV_TR_SHIFT_C5 9
`define TV_TR_SHIFT_F6 9
