// Generated by golden/generate_vectors.py; do not hand edit.
// ---- tb_conv2d_engine.sv (first/legacy module; macros unprefixed) ----
`define TV_IN_H 7
`define TV_IN_W 8
`define TV_IN_CH 3
`define TV_OUT_CH 4
`define TV_OUT_H 3
`define TV_OUT_W 4
`define TV_SHIFT 7
`define TV_RELU 1'b1
`define TV_ACT_COUNT 168
`define TV_WGT_COUNT 300
`define TV_BIAS_COUNT 4
`define TV_CONN_COUNT 12
`define TV_OUT_COUNT 48

// ---- tb_avg_pool2x2_stream.sv ----
`define TV_POOL_IN_H 4
`define TV_POOL_IN_W 6
`define TV_POOL_IN_CH 2
`define TV_POOL_OUT_H 2
`define TV_POOL_OUT_W 3
`define TV_POOL_ACT_COUNT 48
`define TV_POOL_OUT_COUNT 12

// ---- tb_dense_engine.sv (F6 configuration) ----
`define TV_F6_IN_LEN 10
`define TV_F6_OUT_LEN 5
`define TV_F6_SHIFT 6
`define TV_F6_RELU 1'b1
`define TV_F6_ACT_COUNT 10
`define TV_F6_WGT_COUNT 50
`define TV_F6_BIAS_COUNT 5
`define TV_F6_OUT_COUNT 5

// ---- tb_classifier_argmax.sv ----
`define TV_CLS_IN_LEN 6
`define TV_CLS_NUM_CLASSES 4
`define TV_CLS_ACT_COUNT 6
`define TV_CLS_WGT_COUNT 24
`define TV_CLS_BIAS_COUNT 4
`define TV_CLS_EXPECTED_CLASS 3

// ---- tb_requantize.sv ----
`define TV_RQ_COUNT 5504

// ---- tb_lenet5_top.sv ----
`define TV_TOP_EXPECTED_CLASS 6
`define TV_TOP_WATCHDOG_CYCLES 600000
